id: P928232EB
initial_creation_type: ocr
source_metadata:
  volumes:
    405f4c9e5e0f4c628d6f71b43d65714b:
      base_file: v012.txt
      image_group_id: I1PD95857
      title: རྡོ་རྗེ་ཕག་མོའི་སྒྲུབ་པའི་ཐབས།
      total_pages: 1544
      volume_number: 12
