id: D58847384
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-11T09:48:16+00:00'
last_modified: '2022-05-26T08:02:47.318585+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    4a25:
      image_group_id: I1PD95857
      title: རྡོ་རྗེ་ཕག་མོའི་སྒྲུབ་པའི་ཐབས།
      total_pages: 1544
      order: 12
      base_file: 4a25.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
